# Generated by Django 3.2.16 on 2024-02-14 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('first_name', models.CharField(max_length=20, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('full_name', models.CharField(blank=True, editable=False, max_length=50)),
                ('ncode', models.CharField(max_length=11, verbose_name='کدملی')),
                ('scode', models.CharField(max_length=10, verbose_name='کدبیمه ورزشی')),
                ('insurancedate', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ثبت بیمه ورزشی')),
                ('shistory', models.TextField(blank=True, verbose_name='سابقه ورزشی')),
                ('hhistory', models.TextField(blank=True, verbose_name='سابقه پزشکی')),
                ('dob', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('phone1', models.CharField(max_length=20, null=True, verbose_name='شماره تلفن اول')),
                ('phone2', models.CharField(max_length=20, null=True, verbose_name='شماره تلفن دوم')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_time', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated_time', django_jalali.db.models.jDateField(auto_now=True)),
                ('simage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس ')),
                ('rsession', models.IntegerField(default=0, verbose_name='تعداد جلسات باقی مانده')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=20, verbose_name='گذر واژه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_hashed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='SportField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('sport_field', models.CharField(max_length=20, verbose_name='رشته ورزشی')),
            ],
            options={
                'verbose_name': 'رشته ورزشی',
                'verbose_name_plural': 'رشته های ورزشی',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('tfull_name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('tphone', models.CharField(max_length=20, verbose_name='شماره تلفن ')),
                ('tsport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sportfield', verbose_name='رشته ')),
            ],
            options={
                'verbose_name': 'مربی',
                'verbose_name_plural': 'مربی ها',
            },
        ),
        migrations.CreateModel(
            name='SessionDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('dos', django_jalali.db.models.jDateField(verbose_name='تاریخ جلسه')),
                ('session_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
            },
        ),
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('dop', django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت')),
                ('rimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس فیش پرداختی')),
                ('mcharged', models.IntegerField(blank=True, default=0, verbose_name='مقدار پول واریز شده')),
                ('ncharged', models.IntegerField(verbose_name='تعداد جلسات شارژ شده')),
                ('peyment_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'پرداختی',
                'verbose_name_plural': 'پرداختی ها',
            },
        ),
        migrations.CreateModel(
            name='Classi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('cname', models.CharField(max_length=20, verbose_name='نام کلاس ')),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(choices=[('Sat', 'شنبه'), ('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهارشنبه'), ('Thu', 'پنجشنبه'), ('Fri', 'جمعه')], max_length=30)),
                ('starttime', models.TimeField()),
                ('tname', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.trainer', verbose_name='مربی ')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('dot', django_jalali.db.models.jDateField(verbose_name='تاریخ آنالیز')),
                ('current_state_weight', models.FloatField(verbose_name='وضعیت موجود - وزن')),
                ('current_state_bfm', models.FloatField(verbose_name='وضعیت موجود - توده چربی')),
                ('current_state_smm', models.FloatField(verbose_name='وضعیت موجود - عضله ')),
                ('current_state_pbf', models.FloatField(verbose_name='وضعیت موجود - درصد چربی')),
                ('point_state_weight', models.FloatField(verbose_name='هدف مقطعی - وزن')),
                ('point_state_bfm', models.FloatField(verbose_name='هدف مقطعی - توده چربی')),
                ('point_state_smm', models.FloatField(verbose_name='هدف مقطعی - عضله ')),
                ('point_state_pbf', models.FloatField(verbose_name='هدف مقطعی - درصد چربی')),
                ('analysis_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'آنالیز',
                'verbose_name_plural': 'آنالیزها',
            },
        ),
        migrations.CreateModel(
            name='AbsenceDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('doa', django_jalali.db.models.jDateField(verbose_name='تاریخ غیبت')),
                ('absent_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'غیبت',
                'verbose_name_plural': 'غیبتها',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='classname',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.classi', verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='person',
            name='sfield',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sportfield', verbose_name='رشته ورزشی'),
        ),
    ]
