# Generated by Django 3.2.16 on 2024-02-12 19:39

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nextinsurance',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ ثبت بیمه ورزشی'),
        ),
    ]
