# Generated by Django 3.2.16 on 2024-03-26 18:04

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='insurancedate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ثبت بیمه ورزشی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ncode',
            field=models.CharField(blank=True, max_length=11, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('employee', 'کارمند'), ('trainer', 'مربی'), ('student', 'ورزشکار')], default='student', max_length=10, verbose_name='نوع کاربر'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rsession',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد جلسات باقی مانده'),
        ),
    ]
