# Generated by Django 3.2.16 on 2024-02-15 09:25

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_analysis_analysis_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='edu',
            field=models.CharField(blank=True, max_length=50, verbose_name='میزان تحصیلات'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='exp',
            field=models.CharField(blank=True, max_length=50, verbose_name='سوابق تجربی'),
        ),
        migrations.CreateModel(
            name='TrainerSeesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('dos_trainer', django_jalali.db.models.jDateField(verbose_name='تاریخ جلسات')),
                ('class_trainer', models.CharField(max_length=20, verbose_name='نام کلاس')),
                ('session_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainer', verbose_name='نام مربی')),
            ],
            options={
                'verbose_name': 'جلسه مربی',
                'verbose_name_plural': 'جلسات مربی',
            },
        ),
    ]
