# Generated by Django 3.2.16 on 2024-02-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_nextinsurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nextinsurance',
            new_name='insurancedate',
        ),
    ]
