# Generated by Django 3.2.16 on 2024-02-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240215_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='shortdesc',
            field=models.CharField(blank=True, max_length=50, verbose_name='توضیح کوتاه '),
        ),
        migrations.AddField(
            model_name='trainer',
            name='timage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس '),
        ),
    ]
