# Generated by Django 3.2.16 on 2024-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_absencedate_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='گذر واژه'),
        ),
    ]
