# Generated by Django 3.2.16 on 2024-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240221_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, verbose_name='جنسیت'),
        ),
    ]
