# Generated by Django 3.2.16 on 2024-02-21 18:55

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trainer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='dob',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
