# Generated by Django 3.2.16 on 2024-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nextanalysis',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
