# Generated by Django 3.2.16 on 2024-04-08 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_person_nextanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='classi',
            name='ctrainer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مربی کلاس'),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_edu',
            field=models.CharField(blank=True, max_length=250, verbose_name='میزان تحصیلات'),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_exp',
            field=models.CharField(blank=True, max_length=250, verbose_name='سوابق تجربی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_shortdesc',
            field=models.CharField(blank=True, max_length=250, verbose_name='توضیح کوتاه '),
        ),
    ]
