# Generated by Django 3.2.16 on 2024-02-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_person_is_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
