# Generated by Django 3.2.16 on 2024-04-09 20:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_insurance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'بیمه', 'verbose_name_plural': 'بیمه ها'},
        ),
        migrations.AlterField(
            model_name='person',
            name='insurancedate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ بعدی بیمه ورزشی'),
        ),
    ]
