# Generated by Django 3.2.16 on 2024-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20240409_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='t_edu',
            field=models.TextField(blank=True, verbose_name='میزان تحصیلات'),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_exp',
            field=models.TextField(blank=True, verbose_name='سوابق تجربی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='t_shortdesc',
            field=models.TextField(blank=True, verbose_name='توضیح کوتاه '),
        ),
    ]
