# Generated by Django 3.2.16 on 2024-03-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240229_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='diffrence_bfm',
            field=models.FloatField(default=0, verbose_name='وضعیت موجود - توده چربی'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='diffrence_pbf',
            field=models.FloatField(default=0, verbose_name='وضعیت موجود - درصد چربی'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='diffrence_smm',
            field=models.FloatField(default=0, verbose_name='وضعیت موجود - عضله '),
        ),
        migrations.AddField(
            model_name='analysis',
            name='diffrence_weight',
            field=models.FloatField(default=0, verbose_name='وضعیت موجود - وزن'),
        ),
    ]
