# Generated by Django 3.2.16 on 2024-04-09 21:01

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240409_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='nextiInsurancedate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تمدید  بعدی'),
        ),
    ]
