# Generated by Django 3.2.16 on 2024-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20240301_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='diffrence_bfm',
            field=models.FloatField(default=0, editable=False, verbose_name='وضعیت موجود - توده چربی'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='diffrence_pbf',
            field=models.FloatField(default=0, editable=False, verbose_name='وضعیت موجود - درصد چربی'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='diffrence_smm',
            field=models.FloatField(default=0, editable=False, verbose_name='وضعیت موجود - عضله '),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='diffrence_weight',
            field=models.FloatField(default=0, editable=False, verbose_name='وضعیت موجود - وزن'),
        ),
    ]
