# Generated by Django 3.2.16 on 2024-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_insurance_nextiinsurancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='rimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس  بیمه'),
        ),
    ]
