# Generated by Django 3.2.16 on 2024-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_insurance_rimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='classi',
            name='fee',
            field=models.IntegerField(blank=True, default=0, verbose_name='شهریه ۱۲ جلسه'),
        ),
    ]
