# Generated by Django 3.2.16 on 2024-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20240301_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='reportfile',
            field=models.FilePathField(null=True, verbose_name='فایل آنالیز'),
        ),
    ]
