# Generated by Django 3.2.16 on 2024-04-12 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_classi_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف نفر بر روی دوره ها'),
        ),
        migrations.AlterField(
            model_name='classi',
            name='fee',
            field=models.IntegerField(blank=True, default=0, verbose_name=' شهریه ۱۲ جلسه (تومان)'),
        ),
    ]
