# Generated by Django 3.2.16 on 2024-04-13 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_sessiondate_sstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف نفر بر روی دوره ها'),
        ),
    ]
