# Generated by Django 3.2.16 on 2024-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_classi_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classi',
            name='cname',
            field=models.CharField(max_length=20, verbose_name='نام کلاس '),
        ),
    ]
