# Generated by Django 3.2.16 on 2024-03-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_analysis_reportfile_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reportfile',
            field=models.FileField(blank=True, upload_to='', verbose_name='فایل آنالیز'),
        ),
    ]
