# Generated by Django 3.2.16 on 2024-05-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20240504_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='gstock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی کالا'),
        ),
    ]
