# Generated by Django 3.2.16 on 2024-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_goods_gstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='classi',
            name='cgender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
