# Generated by Django 3.2.16 on 2024-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_classi_cgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='changeFlag',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
