# Generated by Django 3.2.16 on 2024-06-17 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_person_changeflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidAbsenceDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('dova', django_jalali.db.models.jDateField(verbose_name=' تاریخ غیبت مجاز')),
                ('classname', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.classi', verbose_name='کلاس')),
                ('vabsent_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'غیبت مجاز',
                'verbose_name_plural': 'غیبتهای مجاز',
            },
        ),
    ]
