# Generated by Django 3.2.16 on 2024-06-19 23:15

from django.conf import settings
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_validabsencedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ردیف')),
                ('aname', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('doa', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ جلسه')),
                ('state', models.CharField(choices=[('absent', 'غییت غیر مجاز'), ('present', 'حاضر'), ('validabsent', 'غیبت مجاز')], default='validabsent', max_length=20, verbose_name='وضعیت حضور')),
                ('aperson', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
        ),
    ]
