# Generated by Django 3.2.16 on 2024-06-19 23:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_attendancesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesheet',
            name='doa',
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_1',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_10',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_11',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_12',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_2',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_3',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_4',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_5',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_6',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_7',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_8',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_9',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='1 تاریخ جلسه'),
        ),
    ]
