# Generated by Django 3.2.16 on 2024-06-19 23:57

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20240620_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_1',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 1'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_10',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 10'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_11',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 11'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_12',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 12'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_2',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 2'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_3',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 3'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_4',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 4'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_5',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 5'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_6',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 6'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_7',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 7'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_8',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 8'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='doa_9',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 9'),
        ),
    ]
