# Generated by Django 3.2.16 on 2024-03-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_analysis_reportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reportfile',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='فایل آنالیز'),
        ),
    ]
