# Generated by Django 3.2.16 on 2024-06-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20240620_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesheet',
            name='aclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.classi', verbose_name='نام کلاس'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='aname',
            field=models.CharField(blank=True, max_length=250, verbose_name='عنوان'),
        ),
    ]
