# Generated by Django 3.2.16 on 2024-06-23 19:49

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20240620_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_13',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 13'),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='doa_14',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name=' تاریخ جلسه 14'),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='state',
            field=models.CharField(choices=[('absent', 'غییت غیر مجاز'), ('present', 'حاضر'), ('validabsent', 'غیبت مجاز'), ('notset', ' وارد نشده ')], default='notset', editable=False, max_length=20, verbose_name='وضعیت حضور'),
        ),
    ]
