# Generated by Django 3.2.16 on 2024-06-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20240623_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesheet',
            options={'verbose_name': 'لیست حضور و غیاب', 'verbose_name_plural': ' لیستهای حضور و غیاب'},
        ),
    ]
