# Generated by Django 3.2.16 on 2024-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20240319_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='نام کاربری'),
        ),
    ]
