# Generated by Django 3.2.16 on 2024-03-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_trainer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='username',
        ),
    ]
