# Generated by Django 3.2.16 on 2024-07-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_person_changeflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
