# Generated by Django 3.2.16 on 2024-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_trainer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='password',
            field=models.CharField(blank=True, max_length=20, verbose_name='گذر واژه'),
        ),
    ]
