# Generated by Django 3.2.16 on 2024-08-16 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_absencedate_absent_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ردیف')),
                ('send_dop', django_jalali.db.models.jDateField(editable=False, verbose_name='تاریخ ارسال')),
                ('send_person', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'ارسال پیامک',
                'verbose_name_plural': 'ارسال پیامکها',
            },
        ),
    ]
