# Generated by Django 3.2.16 on 2024-09-30 04:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_attendancesheet_doa_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastsession',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True),
        ),
    ]
