# Generated by Django 3.2.16 on 2024-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_person_lastsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='peyment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
